#!/usr/bin/tcsh

#-----------------------------------------------------------------------------------------------------------------------------------------------
#
# Author : COSTE Arthur
# Date : May 8th, 2013
#
# Function : Check 
#
# Status : On dev
#
# Version : 
#
# Note : 
#
#-----------------------------------------------------------------------------------------------------------------------------------------------
# Data location

set data_dir = /usr/sci/projects/neuro/clinical_studies/ACE_IBIS/projects/Data_From_UNC/Proc_Data

set output_dir = /usr/sci/projects/neuro/clinical_studies/ACE_IBIS/projects/no_baseline_test/original_colorFA

#-----------------------------------------------------------------------------------------------------------------------------------------------
# Tools

set toolloc = /usr/sci/projects/neuro/software/bin
set dtiprocess_cmd = /usr/sci/projects/neuro/software/bin/dtiprocess

#----------------------------------------------------------------------------------------------------------------------------------------------

echo "---------------------------------------------------------------------------------------------------------------------"
echo
echo "\033[s\033[1;32m\t\t\t\t\t\t begining of test baseline "
echo "\t\t\t\t\t\t version 1 - May 2013 \033[u\033[0m"
echo
echo "---------------------------------------------------------------------------------------------------------------------"

echo
echo "options : "
echo "> Default Verbose Mode: ON"
echo "---------------------------------------------------------------------------------------------------------------------"

#----------------------------------------------------------------------------------------------------------------------------------------------
# Main Code

#set all_cases = $data_dir/??????/V??

#cpt initialization
set cpt = 1
set no_baselinecpt = 1
set nobaseline = ()
set all_cases = `ls $data_dir/*/???/mri/native/DTI/PrelimInclude/*_QCed_DTI.nrrd`
echo $#all_cases
	
foreach dti ($all_cases)

	set case_id = $dti:h:h:h:h:h:h:t
	set case_age = $dti:h:h:h:h:h:t
	set case_directions_directory = $dti:h:t

	set intro = `echo $dti:t | cut -d_ -f1`
	if ($intro == "ibis") then
			
		set a = `echo $dti:t | cut -d_ -f5`
		set acquisition_number = '_'$a
		#echo "acquisition number = $acquisition_number" 	
	
	endif

	if ($intro != "ibis") then

		set ind = `echo $dti:t | cut -c15-16`
		set ind_2 = `echo $dti:t | cut -c19-20`
		#echo $ind
		#echo $ind_2

		if($ind == "_Q") then
		    set ind = ''
		    #echo $ind
	      
		else if ($ind == "_D") then
   
		    if ( $ind_2 == "_2") then
			set ind =  $ind_2 
		else if ($ind_2 == "_3") then
			set ind = $ind_2
		else if ($ind_2 == "_4") then
			set ind = $ind_2 
		else if ($ind_2 == "_5") then
			set ind = $ind_2 
		#else if ($ind_2 == "_6") then
			#set ind = $ind_2 
		else if ($ind_2 == "_7") then
			set ind = $ind_2 
		else if ($ind_2 == "_8") then
			set ind = $ind_2 
		else if ($ind_2 == "_9") then
			set ind = $ind_2 
		    else 
		    set ind = ''
		    #echo $ind

		    endif
		endif
		#echo $ind 
			
		set acquisition_number = $ind
		#echo "acquisition number = $acquisition_number" 	
	
	endif

	echo "processing case $cpt : $case_id $case_age"
	set current_dir = $dti:h
	echo $current_dir
	set dwi = $current_dir/*$acquisition_number'_'QCed.nrrd
	set baseline = `sed -n '16p' $dwi`
	set baseline = `echo $baseline:t | cut -d= -f2`
	set baseline_1 = `echo $baseline:t | cut -d' ' -f1`
	set baseline_2 = `echo $baseline:t | cut -d' ' -f2`
	set baseline_3 = `echo $baseline:t | cut -d' ' -f3`
	
	
	if ($baseline_1 != "0.000000" && $baseline_2 != "0.000000" && $baseline_3 != "0.000000") then
		
		echo "\t baseline : $baseline "		
		echo "\t \033[s\033[1;31mNO BASELINE DETECTED !\033[u\033[0m"		
		set nobaseline = ($nobaseline $case_id'_'$case_age$acquisition_number) 
		@ no_baselinecpt ++

		set colorFA_no_baseline_volume = $output_dir/$case_id'_'$case_age$acquisition_number'_'PrelimInclude_NOBASELINE_ColorFA.nrrd
	
		echo "\033[s\033[1;32mCompute ColorFA 25 dirs >>> \c"
		$dtiprocess_cmd $dti -c $colorFA_no_baseline_volume
		echo "[done]\033[u\033[0m"
		
	endif

	
	

	@ cpt += 1 

end

echo "list of cases with no baseline : $nobaseline"
echo $#nobaseline
